AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  BucketName:
    Type: String
    Default: 'pgr301-couch-explorers'

Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda_folder/
      Handler: app.lambda_handler
      Runtime: python3.10
      Timeout: 30
      Environment:
        Variables:
          BUCKET_NAME: !Ref BucketName
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Action:
                - "s3:PutObject"
              Resource: !Sub "arn:aws:s3:::${BucketName}/*"
            - Effect: "Allow"
              Action:
                - "bedrock:InvokeModel"
              Resource: "*"
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /generate
            Method: POST
Globals:
  Api:
    EndpointConfiguration: REGIONAL


