name: Deploying of the SAM application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy SAM application
    runs-on: ubuntu-latest

    steps:
      - name: Cloning repo
        uses: actions/checkout@v3

      - name: Setting up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10" # same version like used in the code

      - name: Installing AWS SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Configuring AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Building SAM
        run: sam build -t sam_lambda/template.yaml

      - name: Deploying SAM
        run: |
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name Images-Generator-Stack


